### ISSUE TITLE
Testing on a fresh Ubuntu 17.04 install revealed more dependencies

### ISSUE THREAD

**Issue by iopq** [aveferrum/wine-starcraft-installer#2]
1. When you first run it, you'll run into "Attempted to run in 256 color mode.Please verify that compatibility settings are disabled."
2. When you resolve the opengl dependency you still won't have sound

`sudo apt install libgl1-mesa-glx:i386 libasound2:i386 libasound2-plugins:i386` is what I had to do to fix the issues above

you can check if those packages exist and force the user to install them if they're missing

**Comment by edemirkan** [comment]
Thank you for the bug report @iopq 

I added them to dependency check with the following commit; https://github.com/aveferrum/wine-starcraft-installer/commit/ed4d92c030555c144848535ab6282fc3e5493295
