### ISSUE TITLE
Demirkan.info is down, use wine staging instead

### ISSUE THREAD

**Issue by iopq** [aveferrum/wine-starcraft-installer#3]
Right now, the installer stopped working due to the fact that it's trying to download the custom wine version. Since the patches have been staged, it might be prudent to just tell the user to install wine staging instead.

**Comment by edemirkan** [comment]
You're right. I added the following **NOTE** on top of the README.md to inform potential users.
In the following days, I am thinking to update the script to install wine-staging from the official repo. 

`**NOTE**: As of 05/16/2017, all required patches to run StarCraft are included to wine-staging release 2.8. If your distro provides a wine-staging 2.8 package, you're advised to install that instead.`
